"""followers

Revision ID: 5498d7b069b4
Revises: 4ddb1ba1c7c3
Create Date: 2024-10-23 16:58:34.077914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5498d7b069b4'
down_revision = '4ddb1ba1c7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
